name: 'postgres_transformations'
version: '1.0.0'

profile: 'postgres_transformations'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  postgres_transformations:
    example:
      +materialized: table
      +full_refresh: true
      actors:
        +sort_order: null
      films:
        +sort_order: null
      film_actors:
        +sort_order: null